language: node_js

node_js:
  - 'node'

script:
  - npm run lint

notifications:
  email: false
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
    on_success: always # default: always
    on_failure: always # default: always
    on_start: change # default: never
    on_cancel: always # default: always
    on_error: always # default: always
